name: Kotlin EAP CI
on:
  push:
  workflow_dispatch:
    inputs:
      kotlinVersion:
        description: 'Kotlin version'
        required: false

  schedule:
    - cron: '0 0 * * MON'

defaults:
  run:
    shell: bash

jobs:
  kotlin-eap:
    name: ${{ matrix.os }}/${{ matrix.kotlin-version }}/${{ matrix.try-next }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        try-next: [ 'true', 'false' ]
        kotlin-version:
          - '' # uses current project version
          - ${{ inputs.kotlinVersion || '2.1.20-dev-+' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
        with:
          cache-disabled: true

      - run: >
          ./gradlew
          build publishToMavenLocal linkAll
          --continue
          -Pckbuild.skipTestTasks=true
          -Pckbuild.warningsAsErrors=false
          -Pckbuild.kotlinVersionOverride=${{ matrix.kotlin-version }}
          -Pkotlin.experimental.tryNext=${{ matrix.try-next }}
